FROM eclipse-temurin:17-jdk-jammy AS build

WORKDIR /app

COPY pom.xml .

RUN ./mvnw dependency:go-offline

COPY src ./src
COPY mvnw .
COPY .mvn .mvn

RUN chmod +x ./mvnw

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

ARG PORT=8080

EXPOSE ${PORT}

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
