FROM openjdk:17-jdk-slim AS build

WORKDIR /app

COPY pom.xml .

RUN ./mvnw dependency:go-offline

COPY src ./src
COPY mvnw .
COPY .mvn .mvn

RUN chmod +x ./mvnw

RUN ./mvnw clean package -DskipTests


FROM openjdk:17-jre-slim

WORKDIR /app

ARG PORT=8080

EXPOSE ${PORT}

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
